# Generated by Django 5.1.2 on 2024-10-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='di', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('symptoms', models.TextField()),
                ('date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('valid', 'Validé'), ('invalid', 'Invalidé')], default='invalid', max_length=10)),
            ],
        ),
    ]
