# Generated by Django 5.1.2 on 2024-10-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('validé', 'Validé'), ('invalidé', 'Invalidé')], default='invalidé', max_length=10),
        ),
    ]
